/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test 
    void Test_registrar_usuario(){
        App classUnderTest = new App();
        List<Usuario> usuarios = classUnderTest.getUsuarios(); 
        classUnderTest.registrar_usuario("marta","marta@gmail.com", 1); 
        List<Usuario> usuarios2 = classUnderTest.getUsuarios(); 
        usuarios.add(new Usuario("marta","marta@gmail.com", 1));
        
        assertArrayEquals(usuarios.toArray(), usuarios2.toArray());  
    }
    @Test 
    void Test_eliminar_usuario(){
        App classUnderTest = new App();
        List<Usuario> usuarios = classUnderTest.getUsuarios(); 
        classUnderTest.eliminar_usuario("marta", "marta@gmail.com", 1);
        List<Usuario> usuarios2 = classUnderTest.getUsuarios(); 
        usuarios.remove(new Usuario("marta","marta@gmail.com", 1)); 
        
        assertArrayEquals(usuarios.toArray(), usuarios2.toArray());  
    }
    @Test 
    void Test_registrar_habitaciones(){
        App classUnderTest = new App();
        List<Habitacion> habitaciones = classUnderTest.getHabitaciones(); 
        classUnderTest.añadir_habitacion("media",30, 1); 
        List<Habitacion> habitaciones2 = classUnderTest.getHabitaciones(); 
        habitaciones.add(new Habitacion("media",30, 1)); 
        
        assertArrayEquals(habitaciones.toArray(), habitaciones2.toArray());  
    }
    @Test 
    void Test_eliminar_habitaciones(){
        App classUnderTest = new App();
        List<Habitacion> habitaciones = classUnderTest.getHabitaciones();
        classUnderTest.eliminar_habitacion("media",30, 1); 
        List<Habitacion> habitaciones2 = classUnderTest.getHabitaciones(); 
        habitaciones.remove(new Habitacion("media",30, 1)); 
        
        assertArrayEquals(habitaciones.toArray(), habitaciones2.toArray());  
    }
    @Test 
    void Test_listar_habitaciones(){
        App classUnderTest = new App();
        classUnderTest.añadir_habitacion("individual", 15, 9);
        List<Habitacion> habitaciones  = classUnderTest.listar_habitacion();
        List<Habitacion> habitaciones2 = classUnderTest.listar_habitacion();

        assertArrayEquals(habitaciones.toArray(), habitaciones2.toArray()); 
    }
    @Test
    void Test_hacer_reserva(){
        App classUnderTest = new App();
        Map<String, List<Reserva>> reservas = classUnderTest.listar_reservas();
        classUnderTest.añadir_habitacion("individual", 15, 4);
        Usuario usuario = new Usuario("Marc", "marc@gmail.com", 5);
        classUnderTest.hacer_reserva(4, usuario);
    
        Map<String, List<Reserva>> reservas2 = classUnderTest.listar_reservas();
        List<Reserva> reservasMarc = reservas.getNombre("Marc");

        assertArrayEquals(reservas.toArray(), reservas2.toArray()); 
    }
    @Test
    void Test_listar_reservas(){
        App classUnderTest = new App();
        Map<String, List<Reserva>> reservas  = classUnderTest.listar_reservas();
        Map<String, List<Reserva>> reservas2 = classUnderTest.listar_reservas();

        assertArrayEquals(reservas.toArray(), reservas2.toArray()); 
    }
    
    


}
